lsコマンド提出用
eatplaynap/ruby-practices pull request #16
Opened 2021-03-02 12:15 UTC by eatplaynap

2021-03-03 02:55 UTC, komagata requested changes

2021-03-03 02:55 UTC, komagata commented on 05.ls/ls.rb
> +    permissions_trio = last_three_digits.map do |digit|
permissions_trioのtrioってなんでしょう？

2021-03-03 06:23 UTC, eatplaynap commented on 05.ls/ls.rb
> +    permissions_trio = last_three_digits.map do |digit|
オーナー、グループ、その他ユーザーの3つのパーミッションをまとめた文字列を返すので、三つ組の意味でトリオを使ってみました。

2021-03-04 04:09 UTC, komagata commented on 05.ls/ls.rb
> +    permissions_trio = last_three_digits.map do |digit|
なるほどです！

2021-03-04 04:12 UTC, komagata requested changes

2021-03-04 04:12 UTC, komagata commented on 05.ls/ls.rb
> +  require 'etc'
絶対なしというわけでは無いのですが、requireはロジックによって読み込まれたり読み込まれなかったりしないように一番上にまとめて書くのが一般的なので特に強いこだわりがなければそうするのがいいかもです。

2021-03-04 05:12 UTC, eatplaynap commented on 05.ls/ls.rb
> +  require 'etc'
了解しました！特にこだわりはないのでまとめてみました。

2021-03-04 07:35 UTC, komagata approved these changes
いい感じだと思います、OKです〜！

2021-03-04 07:50 UTC, merged