OOP版ボウリングプログラム
eatplaynap/ruby-practices pull request #18
Opened 2021-10-01 13:03 UTC by eatplaynap

下記のクラスを作成し、それぞれに対してテストを作成しました。
- Gameクラス
- Frameクラス
- Shotクラス

2021-10-06 01:53 UTC, u1tnk requested changes
全体的にほぼ問題無いので細かいところに目が行って色々指摘してしまいました。
Shotの使い方のところと名前付け(名前は大事なんです)のところは修正必須ですが、他はわりと細かいところなので、お任せします。

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    fallen_pins = frame_details.map(&:score)
細かいんですが、 他のところは `pins`なのにここだけ `fallen_pins`だと意図が分かりづらいです。
X入りと無しと意味も多少違うからでしょうか？

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +          frame.clear
かなり細かいんですが、

```
frames << frame
frame = []
```

の方が素直に読めるかなと思いました。

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +      if frames.size < 10
ここは一個のifの方が見やすいかな？ 微差ですが。
で、条件は以下の方がやりたい事にあってるかなと思いました。10番目じゃないし、10番目以外なら3投しませんから。

あとnext使うと elseじゃなくなって、ちょっっっとだけ見やすくなるかと。
```
if frames.size != 10 && (frame.size == 2 || pin == 'x')
    ....
  next
end
```

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +  def frame_details
これ initializeでやってしまって一回変数に入れると良いですね。Frameオブジェクトにした後変更も無いので。
計算だけなので大したコストでは無いとはいえ、呼ばれる度にsplit_all_pins_into_framesまで全部やっているわけですし。

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +  def split_all_pins_into_frames
ロジックすっきりしてますね 👍 
each_slice(2)を使う方が多いんですが、全部のフレームが2つじゃないので、結構調整が必要なので、このように自作の条件だけで分割する方が分かりやすいですね。

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +      array.frame.map { |c| c == 'X' ? 10 : c.to_i }
Shotクラスがあるのに `next_shots`で数値が返ってくるのは混乱するので良くないですね。
また、 Xのときにスコア10になるのはShotで実装済みなのでそこが統一できてないのも良くないです。

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +if __FILE__ == $PROGRAM_NAME
これでも全然良いんですが、現在も複数ファイルで構成されていますし、 `bowling.rb`とか別に作ってそこからgameを呼ぶ方がif文不要でスッキリする気がします。

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/test/frame_test.rb
> +# frozen_string_literal: true
Gameのテストだけでも大体カバーできるのにFrameも単体でテストしているのは良いですね 👍

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @frame = frame
frameクラスに`@frame`があって、frameオブジェクトが入ってないのは混乱を招くのでNGです。

2021-10-06 01:53 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @first_shot = Shot.new(frame[0])
これでも良いですが、 `@shots = [....]`と配列になっていた方が良いですね。
rubyl/railsプログラマの慣習として英単語複数形の変数があると「英単語のクラスのインスタンスが入っている配列」と判断するので。

2021-10-06 06:02 UTC, eatplaynap commented on 07.bowling_object/lib/frame.rb
> +    @first_shot = Shot.new(frame[0])
`@shots`にShotインスタンスが入るように修正しました！

2021-10-06 06:02 UTC, eatplaynap commented on 07.bowling_object/lib/frame.rb
> +    @frame = frame
なるほど…！変数名を`@rolls`に変更してみました。

2021-10-06 06:07 UTC, eatplaynap commented on 07.bowling_object/lib/game.rb
> +  def frame_details
initializeで`@frame_details`変数を定義しました！

2021-10-06 06:58 UTC, eatplaynap commented on 07.bowling_object/lib/game.rb
> +      array.frame.map { |c| c == 'X' ? 10 : c.to_i }
メソッド名を`remaining_rolls`に変更しました〜
また、Framesクラスで定義した`@shots`にnilが入らないように変更し、新たに各フレームのscoreを数値の配列として返す`shots_to_i`メソッドを定義しました〜

2021-10-07 12:33 UTC, eatplaynap commented on 07.bowling_object/lib/game.rb
> +      if frames.size < 10
こちら、each文を下記のように書きなおしてみたところ、うまく動かなくなりました💦
```ruby
pins_in_an_array.each do |pin|
      if frames.size != 10 && ( frame.size == 2 || pin == 'X' )
        frame << pin
        frames << frame
        frame = []
        next
      end
    end
```
問題が2点あって、こちらをクリアするコードが書けないので、できれば修正前のままで行きたいです🙏
1. 第1投目が’X'以外だったとき、ifの条件に合致しないため、処理の流れを新しく考え直す必要がある
1. nextを使って書き換えたとき、ターキーのときの最後の投球を反映させるロジックが書けない

2021-10-08 01:23 UTC, u1tnk requested changes
疑問点のところコメントしました。
また、「修正しました」となっているところも反映されてないようですが、まだpushしてないですか？？

2021-10-08 01:23 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +      if frames.size < 10
元々細かい指摘だったし、正直好みのレベルなので戻しても良いのですが、等価と思ってたのでちょっと気になります 🤔 疑問点をそのままにするのは良くないと思うのでちょっと確認させてください。


> 第1投目が’X'以外だったとき、ifの条件に合致しないため、処理の流れを新しく考え直す必要がある

1フレーム目の第1投目が9のときは ifに入らずに `frames.last << pin` して、2投目で ifに入るはず…と思ったところで気づきましたが この時点では `frame.size`は1なので確かに入りませんね。とはいえ `frame.size >= 2`でも同じく入らないので同じになりそうですが、違います？

> nextを使って書き換えたとき、ターキーのときの最後の投球を反映させるロジックが書けない

これは10フレ目の事でしょうか？
それ以外のストライクは全てifに入るはずだし、10フレ目は ` frames.size != 10 ` なので全て ifの下に行くので 全て frames.lastに入るのでは無いでしょうか？

2021-10-08 05:36 UTC, eatplaynap commented on 07.bowling_object/lib/game.rb
> +      if frames.size < 10
> とはいえ frame.size >= 2でも同じく入らないので同じになりそう

ネストしているifの中にelseの処理がなかったので分かりづらいかもなのですが、`frame.size >= 2 || pin == 'X'`がfalseの場合は何もせずにeach文に戻るはずです…(下記コードで確認してみました)！
```
 (1..10).each do |x|
   if x != 10
     if x.even?
       puts "#{x}は偶数"
     else
       puts "Do nothing"
     end
   else
     puts "#{x}は最後の値"
   end
 end
```

なので2投目のpinの評価が始まり、`frame.size >= 2 || pin == 'X'`がtrueになったタイミングで`frames`に`frame`が格納され、またeachに戻るので、フレームごとの二重配列が作れています。

> 10フレ目は frames.size != 10 なので全て ifの下に行くので 全て frames.lastに入る

仰る通りでした…！`frames.last << pin`を書く場所をeachのendの後に書いていたため、うまく動いていなかったようです！

2021-10-09 13:06 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +      if frames.size < 10
> 、frame.size >= 2 || pin == 'X'がfalseの場合は何もせずにeach文に戻るはずです…(下記コードで確認してみました)！

ああー。 ifを一個にまとめたことで、falseのときに framesにpushしちゃってたんですね。
なるほど、そのケースを見逃してましたね。

スッキリしました！
ちゃんと動く、お好みの状態にしておいてください 🙏

2021-10-09 13:15 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +        else
僕が勘違いしていてなんですが、 else節無くて大丈夫です 🙏

2021-10-09 13:15 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +        next
これはとりいれて頂いた感じですね 👍

2021-10-09 13:15 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +          frame.clear
これ駒形さんのお手本にあったみたいですね 😅 
好みの範疇ではあると思います！

2021-10-09 13:37 UTC, u1tnk requested changes
確認しました！

またですが、完成度が高いので細かいところ気になってますね  😓 

shots_to_iのところも見直すと細かいなぁとは思うのですが、「なるべくオブジェクトの状態で受け渡す方が混乱が少なく、柔軟性が高い」という事を伝えたかったです。

2021-10-09 13:37 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +  def remaining_rolls(index)
これはそのままto_iして shotsを返せば良いと思います。
実質変わらないと思われるかもしれませんが、オブジェクトのまま返して、数値が必要なところでオブジェクトから数値にした方が柔軟性が高いし、シンプルになりますね。
rollからshot作ってるのにまたrollにしちゃうのも不自然ですし。

ちなみにこのケースだとほとんど変わりませんが、計算するときにオブジェクトの他の情報が必要になるとかよくあります。

2021-10-09 13:37 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +        remaining_rolls(index).first(2).sum
shotsオブジェクトが返ってると仮定すると  `remaining_rolls(index).first(2).sum{_1.score}` で良いと思います。

2021-10-09 13:37 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    frames
Frameを作る材料を分割しているだけのはずなので `frames.map{Frame.new(_1)}` で返して良いと思い

2021-10-09 13:37 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    @frame_details = split_all_pins_into_frames.map { |n| Frame.new(n) }
frame_details という変数名ですが `@frames` で良いと思い

2021-10-09 13:37 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    @frame_details[index.succ..-1].map(&:shots_to_i).flatten
ちなみにこの、「残りのFrameからshot集めてきて最初の2つ」という発想に至ってる方は少ないですよ。プロレベル！ 👍

2021-10-09 13:37 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +  def shots_to_i
後述した処理にするとここは必要無いと思います。

上のscoreは「Frameのscoreはこの内容です」という定義をしているので必要ですが、
`frame.shots_to_i` と `frames.shots.map(&:score)` であまり情報量変わりませんし。
`attr_reader :shots` は必要になりますね。

2021-10-13 00:30 UTC, u1tnk requested changes

2021-10-13 00:30 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @shots = [Shot.new(rolls[0]), Shot.new(rolls[1]), Shot.new(rolls[2])].reject { |shot| shot.mark.nil? }
`rolls.reject {_1.nil?}.map{Shot.new(_1)}`
で良いかなと思いますが、そもそも rollsにnilが入るケースあるんでしょうか？ 🤔

2021-10-13 00:30 UTC, u1tnk commented on 07.bowling_object/lib/shot.rb
> +  attr_reader :mark
他全て rollになってると思うので markと意味の違いが無ければ rollで統一するようにしましょう。

2021-10-13 01:21 UTC, eatplaynap commented on 07.bowling_object/lib/frame.rb
> +    @shots = [Shot.new(rolls[0]), Shot.new(rolls[1]), Shot.new(rolls[2])].reject { |shot| shot.mark.nil? }
この書き方だとnilになるケースはなさそうなので、`@shots = rolls.map{Shot.new(_1)}`に変更しました！
(10フレーム目まで存在しない`Shot.new(rolls[2]`を含んだ配列を基準に考えていたので、nilを排除する必要がありました)

2021-10-13 07:24 UTC, u1tnk approved these changes
最後一個コメントしましたが、細かいのでOKです 🙆‍♀️

2021-10-13 07:24 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @rolls = rolls
`@rolls`は直下以外で使ってないと思うので、保存しないで大丈夫です。`@shots`を通じて取得もできますし。

2021-10-16 01:01 UTC, merged