オブジェクト指向版lsコマンド
eatplaynap/ruby-practices pull request #19
Opened 2021-11-06 00:10 UTC by eatplaynap

2021-11-12 01:35 UTC, u1tnk requested changes
入力処理あたりすっきり終わっているし、クラスの使い方もオブジェクト指向としてちゃんとできていますね。

これで合格でも問題無いかなーとも思いますが、せっかくなのでもう一声 💪 

LongFormat が長いので、クラスの分割を考えましょう。
LongFormatなのにで、ファイル名からファイルの情報を引き出す処理が多いんですよね。
名前と内容が少しあっていないので、そこらへんを分離できるとより良くなるのでやってみましょう 💪

2021-11-12 01:35 UTC, u1tnk commented on 08.ls_object/lib/short_format.rb
> +  def pad_with_space
paddingですか？ calもそうですが、とりあえずは略さないようにしましょう。

参考 :  https://blog.jnito.com/entry/2020/10/20/092724

2021-11-12 01:35 UTC, u1tnk commented on 08.ls_object/lib/command.rb
> +ls = Command.new
ものすごい細かいんですが、 

```
command = Command.new
command.main
```

で良いかなと。クラス名と変数名が違うと「何か意味がある？」と考えてしまうので。

2021-11-12 01:35 UTC, u1tnk commented on 08.ls_object/lib/command.rb
> +    if @opt['l']
細かいですが

```
format = if @opt['l']
略
end
format.format
```

と、共通の変数に入れて共通のメソッドを呼ぶ方がrubyのduck typing使っていてよりオブジェクト指向感ありますね。

2021-11-12 01:35 UTC, u1tnk commented on 08.ls_object/lib/short_format.rb
> +class ShortFormat
Formatも名詞でもあるのでダメでは無いのですが、動詞でもあるので `LongFormat.format`と同じ単語が続いてちょっと気持ち悪いです。
Formatter とするとより良いと思います。

2021-11-14 02:07 UTC, eatplaynap commented on 08.ls_object/lib/short_format.rb
> +  def pad_with_space
詰めるという動詞としてpadを使ってましたが、確かに分かりづらいのでpaddingに修正しました〜😄

2021-11-14 06:54 UTC, eatplaynap commented on 08.ls_object/lib/command.rb
> +    if @opt['l']
言われてみると、こんな書き方ができるんですね〜！めっちゃスッキリしました！

2021-11-14 07:27 UTC, eatplaynap commented on 08.ls_object/lib/short_format.rb
> +class ShortFormat
ShortFomatクラス→ShortFormatterクラス、LongFormatクラス→LongFormatterクラスにそれぞれ変更しました〜！

2021-11-14 08:21 UTC, u1tnk requested changes
一点クラスの責務とメソッドの場所があっていないのでそこを調整お願いします。


以下やる必要は無いです。今後の参考まで。

- file_info(infomationは複数形にならないので悪くは無いけど、他の名前を使った方が使いやすい。
- file_namesを取得するときに同時にFileInfoの配列にするとformatterからFileInfoの生成も独立できる
    - inputの生情報よりオブジェクトにした方がどこで情報が必要になってもすぐに使えるし、複数の場所でオブジェクト化したりする事が無いのでより良い。
    - ShortFormatterがfile_nameしか必要としないので今回は特にメリットが無いのでやらなくて良いです。

2021-11-14 08:21 UTC, u1tnk commented on 08.ls_object/lib/file_info.rb
> +  def assemble_file_infos
これはLongFormatter専用になるメソッドなのでLongFormatterが持つべきです。
FileInfoクラスはFileの情報を取得する役目に徹しましょう。

2021-11-16 01:05 UTC, u1tnk requested changes
すみません、前回一点見逃しておりました。
まあ一点だけ細かめのところで修正点も明確なのでこれで OKとします。
あとで修正しておいてもらえればと。

2021-11-16 01:05 UTC, u1tnk commented on 08.ls_object/lib/file_info.rb
> +  def get_file_info
細かいですが、 rubyでは `get_`/`set_` は基本書かないですね。 これだったら `file_info`とします…が… これ `FileInfo`クラスか。
私だったら何度も呼んでいてその度にファイルアクセスしてる(1ファイルへのアクセスなので問題になるほどじゃないですがIO処理はちょっと重いです)ので initalizeで実行して 使ってるのが `File::Stat` なので`@file_stat` とするかな 🤔

2021-11-16 01:05 UTC, u1tnk approved these changes

2021-11-16 01:49 UTC, merged